apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-example-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-example-app
  template:
    metadata:
      labels:
        app: my-example-app
    spec:
      containers:
        - name: my-example-app
          imagePullPolicy: IfNotPresent # use local image built in minikube
          image: example-docker-image:latest
          ports:
            - containerPort: 8080

