apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  namespace: app-prod
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /echo
        pathType: ImplementationSpecific
        backend:
          service:
            name: echo
            port:
              number: 1027
      - path: /ingress
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-example-service
            port:
              number: 80
